### ISSUE TITLE
Check validity of test

### ISSUE THREAD

**Issue by sumeetjain** [omahacodeschool/ruby-toy__first-non-repeated-letter#2]
@andrewek Can you verify this change I've made to a test is correct? I'm pretty sure it is, but a non-trivial part of my has major self-doubt about it–like I'm missing something obvious. :)

https://github.com/omahacodeschool/ruby-toy__first-non-repeated-letter/commit/c899e090743c873f1e9e82ed6305b2bca3e024b5

**Comment by andrewek** [comment]
Your change is absolutely correct. Sorry about that.

**Comment by sumeetjain** [comment]
No biggie–just wanted to make sure I wasn't missing something. Thanks! :+1:
